### ISSUE TITLE
Use first line as a title

### ISSUE THREAD

**Issue by myxa777** [trey-wallis/obsidian-note-splitter#17]
If "Use first line as a title" is switched on AND first line of a note contains for example a link or some special symbols, then Note-Splitter generates error and skippes the note.

In fact it is not necessary to copy links and other symbols from the note body to the note name.

When generating note's name from the first line you can replace special symbols with a space symbol for example.

![photo_2024-09-02_13-35-42](https://github.com/user-attachments/assets/dfdb0f55-c69a-480e-9cc6-f1769adb4f5d)

**Comment by decaf-dev** [comment]
@myxa777 Thank you for this bug report. Could you provide me an example or two of file names that aren't working? In addition, what is your operating system? Is it Windows? There are differences in which characters are accepted between operating systems.

**Comment by myxa777** [comment]
I wanted to split a long note by \n (one para = one note). The long note could look like this:

buy milk/bread/water #todohome
https://github.com/decaf-dev/obsidian-note-splitter/issues/17
some long sentence with some \ or / or : etc. symbols
etc
etc
etc

**Comment by decaf-dev** [comment]
@myxa777 Thank you for the example. It helped me to review the code and find a few bugs. I did forget to remove some characters that are prohibited on Windows. Please try 1.2.1 and let me know if it solves the issue.

**Comment by decaf-dev** [comment]
I also added a list of the characters that are now being removed to the documentation.

**Comment by decaf-dev** [comment]
Closing this for now. Please comment if you run into any other issues. Thank you :)
