### ISSUE TITLE
Doesn't work at all for me.

### ISSUE THREAD

**Issue by Onneit** [trey-wallis/obsidian-note-splitter#5]
Nothing happens using hotkey. Plugin doesn't show up in command palette although fully installed and enabled. please help?

**Comment by decaf-dev** [comment]
Hi @Onneit. You need to open your markdown file and be in editing mode.

**Comment by decaf-dev** [comment]
@Onneit The command is always available in the command palette now in 1.1.0. Please update the plugin. Thanks!

**Comment by Onneit** [comment]
Great! Thanks so much.
